### ISSUE TITLE
`dbx deploy` fails with `AttributeError: 'bytes' object has no attribute 'suffixes'` 

### ISSUE THREAD

**Issue by arturomf94** [databrickslabs/dbx#387]
## Expected Behavior

I'm deploying with the following:

```
dbx deploy --environment=ENV --deployment-file=PATH_TO_DEPLOYMENT_FILE.yaml --no-rebuild
```

Deployment is successful with `dbx=0.5.0` but fails with the latest, `0.6.12`, version.

## Current Behavior

I'm getting the following error:

```                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 1660579771264 | ERROR:scripts.data_science_libs.process.execute - stderr: Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 1660579771264 |   File "/root/.pyenv/versions/3.8.13/bin/dbx", line 8, in <module>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 1660579771264 |     sys.exit(cli())                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| 1660579771264 |   File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/click/core.py", line 829, in __call__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| 1660579771264 |     return self.main(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 1660579771264 |   File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/click/core.py", line 782, in main                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 1660579771264 |     rv = self.invoke(ctx)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| 1660579771264 |   File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/click/core.py", line 1259, in invoke                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 1660579771264 |     return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 1660579771264 |   File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/click/core.py", line 1066, in invoke                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| 1660579771264 |     return ctx.invoke(self.callback, **ctx.params)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| 1660579771264 |   File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/click/core.py", line 610, in invoke                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 1660579771264 |     return callback(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 1660579771264 |   File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/dbx/commands/deploy.py", line 149, in deploy                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 1660579771264 |     config_reader = ConfigReader(deployment_file, jinja_variables_file)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 1660579771264 |   File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/dbx/api/config_reader.py", line 71, in __init__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 1660579771264 |     self._path = self._verify_deployment_file(path) if path else self._find_deployment_file()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 1660579771264 |   File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/dbx/api/config_reader.py", line 76, in _verify_deployment_file                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| 1660579771264 |     file_extension = candidate.suffixes[-1]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 1660579771264 | AttributeError: 'bytes' object has no attribute 'suffixes'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
```

## Context

I believe the error comes from some issue with `pathlib`. However, I'm not sure why this would change betweeen `0.5.0` and `0.6.12`. 

I haven't tried any other versions in-between those two, but I will try to see if it works with anything `>0.5.0` and leave a comment here.

## Your Environment

* dbx version used: 0.6.12
* Databricks Runtime version: [Databricks Runtime 9.1 LTS for Machine Learning](https://docs.databricks.com/release-notes/runtime/9.1ml.html)

**Comment by renardeinside** [comment]
hi @arturomf94 , 
could you please check if this error is reproducible with `dbx==0.6.11`?

**Comment by renardeinside** [comment]
I've tried to reproduce this error with dbx==0.6.12 and dbx==0.6.11 in my environment, but unfortunately couldn't - it's working as expected.

**Comment by arturomf94** [comment]
I've tried to go all the way down to `dbx==0.6.0` and it also fails, but with a different error:

```
ModuleNotFoundError: No module named 'dbx.api.storage'
```

🤔

**Comment by renardeinside** [comment]
`dbx.api.storage` issue was a bug in 0.6.0, this is irrelevant to the current one. 

Could you please try the following:
```
pip uninstall dbx
pip install -U dbx
```

**Comment by arturomf94** [comment]
@renardeinside - took me a while, but I think I've found what it is... 

I reckon it's an issue with `click`. I was using version `7.1.2`, which apparently fails to parse the path as a string. If I upgrade the version to, for instance, `8.1.0`, then it works. 

In order to replicate:

1. Install `click==7.1.2`.
2. Run the following:

```python
from pathlib import Path
import click


@click.command()
@click.option(
    "--path",
    required=False,
    type=click.Path(path_type=Path),
    help="path",
    is_eager=True,
)
def test(path):
    print(Path(path).suffixes)


if __name__ == "__main__":
    test()
```

This will fail with something like: `TypeError: argument should be a str object or an os.PathLike object returning str, not <class 'bytes'>`

I can upgrade my `click` version, but I think it might be worth upgrading the requirements in `dbx` so as to avoid these issues! :)

**Comment by renardeinside** [comment]
hi @arturomf94 , 

ah, this makes sense now! we're anyways changing CLI interfaces from click to typer so in upcoming release this shouldn't be a problem. 

Thanks a lot for raising the issue!
