### ISSUE TITLE
Error when requests==2.30.0

### ISSUE THREAD

**Issue by RinatVeliakhmedov-TomTom** [databrickslabs/dbx#764]
`dbx` specifies ` "requests>=2.24.0, <3.0.0"`, but with `requests-2.30.0` it will fail with `AttributeError: type object 'Retry' has no attribute 'DEFAULT_METHOD_WHITELIST'`. The same commands work fine with `requests-2.29.0`.

See [stackoverflow](https://stackoverflow.com/questions/65289720/attributeerror-retry-object-has-no-attribute-method-whitelist).
The reason is that `requests 2.30.0` will allow for 

```
Collecting urllib3<3,>=1.21.1 (from requests<3.0.0,>=2.24.0->dbx==0.8.8)
  Downloading urllib3-2.0.2-py3-none-any.whl (123 kB)
```

but `requests 2.29.0` will result in

```
 Collecting urllib3<1.27,>=1.21.1 (from requests<3.0.0,>=2.24.0->dbx==0.8.8)
  Downloading urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
```

## Steps to Reproduce (for bugs)

Install dbx with `requests==2.30.0`, update `urllib3` package, and try deploying a workflow. It will fail with the error above.
Reinstall it with `requests==2.29.0` and it will work.

## Your Environment

* dbx version used: 0.8.8
* Databricks Runtime version: 11.3

Python 3.9

**Comment by kparaju** [comment]
This is related to https://github.com/databricks/databricks-cli/issues/636

**Comment by fillipemadureira** [comment]
I've had the same issue. For now, my solution is to fix requests to version 2.29.0

**Comment by renardeinside** [comment]
Hi everyone on this thread, 
thanks a lot for timely reporting the issue. It's unfortunate that minor release broke the dependency chain. 
I'll release a fix during this weekend.

**Comment by renardeinside** [comment]
closed in linked PR and released in 0.8.12. Please check if everything works as expected, and thanks a lot for opening the issue @RinatVeliakhmedov-TomTom and exploring the fixes!
